# Site settings
name: 小鑫
location: 黔南
company: IBM
position: 后端cv开发工程师
github: https://github.com/Programmer2416611057/Gitee
facebook: https://www.facebook.com/
phone:  158785298954
email: 2416611057@qq.com

baseurl: "/resume.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

